name: municipal_e_challan
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  barcode_widget: ^2.0.4
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  permission_handler: ^12.0.1
  carousel_slider: ^5.1.1
  intl: ^0.20.2
  printing: ^5.14.2
  pdf: ^3.11.3
  lottie: ^3.3.1
  animate_do: ^3.3.4
  shimmer: ^3.0.0

  
  # BLoC State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  
  # HTTP and Networking
  http: ^1.5.0
  
  # Dependency Injection
  get_it: ^7.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  # Testing
  bloc_test: ^9.1.5
  mockito: ^5.4.4
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/icons/issue_challan.png
    - assets/icons/view_challan.png
    - assets/images/clean_city.jpg
    - assets/images/clean_city.png
    - assets/icons/report.png
    - assets/icons/regulation.png
